version: "3.8"

services:
  portfolio:
    image: aneeshpissay/portfolio:latest
    # OR build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
    # optionally:
    # network_mode: "bridge"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=aneesh-pissay.cloud
    depends_on:
      - portfolio

# Force the default network to use the bridge driver (prevents overlay/stack networks)
networks:
  default:
    driver: bridge
