name: CI/CD — Build Docker, Push to Docker Hub, Deploy to Hostinger

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio

jobs:
  build_and_push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:${{ github.sha }}

      - name: Save image info
        run: echo "IMAGE=${{ env.IMAGE_REPO }}:latest" >> $GITHUB_ENV

  deploy_hostinger:
    name: Deploy to Hostinger
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Hostinger VM
        uses: hostinger/deploy-on-vps@v2
        with:
          api-key: ${{ secrets.HOSTINGER_API_KEY }}
          virtual-machine: ${{ secrets.HOSTINGER_VM_ID }}

      - name: Post-deploy info
        run: |
          echo "Deployed $IMAGE to Hostinger VM ${{ secrets.HOSTINGER_VM_ID }}"
